version: '3.1'

volumes:
  db_data:

services:
  postgres:
    container_name: postgres_${POSTGRES_VERSION:-latest}
    restart: always
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data/${POSTGRES_VERSION:-latest}
    volumes:
      - db_data:/var/lib/postgresql/data/${POSTGRES_VERSION:-latest}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  adminer:
    container_name: db_adminer_${POSTGRES_VERSION:-latest}
    image: adminer
    restart: always
    ports:
       - ${ADMINER_PORT:-8080}:8080
